### ISSUE TITLE
Error while creating wiki

### ISSUE THREAD

**Issue by revi** [Orain/CreateWiki#18]
Please see the previous discussions on Orain/ansible-playbook#591.
Original description:
When I tried to create wikis using [[[meta:Special:CreateWiki]]](https://meta.orain.org/wiki/Special:CreateWiki), I got the following error; Wiki was created while error was displayed.

    Unexpected non-MediaWiki exception encountered, of type "BadMethodCallException"

**Comment by addshore** [comment]
This error should no longer occur (sure its been replaced by a different error on orain) but that's an orain issue
