### ISSUE TITLE
CreateWiki doesn't create CF records

### ISSUE THREAD

**Issue by NDKilla** [Orain/CreateWiki#21]
Hopefully everyone looking at this is already aware of this.

I talked to @Southparkfan  and @FastLizard4  a lot about this today while reading the CF API documentation.

I'm kind of hoping #20 fixes this but will look into it more if not..
Basing ^ off of discussions with the two users above and reading on the documentation that 'tkn' and 'email' must be passed in the api request.

-fingers crossed-

**Comment by addshore** [comment]
Merged #20 per the docs at https://www.cloudflare.com/docs/client-api.html#s2.1
Apparently the lib I included is wrong then? :/

**Comment by addshore** [comment]
It does now
